# Generated by Django 2.1.4 on 2019-02-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_link_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('bought', models.DateField()),
                ('bought_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='stores',
            field=models.ManyToManyField(related_name='items', to='lists.Store'),
        ),
        migrations.AddField(
            model_name='house',
            name='faveStores',
            field=models.ManyToManyField(related_name='houses', to='lists.Store'),
        ),
        migrations.AddField(
            model_name='house',
            name='items',
            field=models.ManyToManyField(related_name='houses', to='lists.Item'),
        ),
        migrations.AddField(
            model_name='house',
            name='users',
            field=models.ManyToManyField(related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
