# Generated by Django 2.1.4 on 2019-02-25 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190225_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='faveStores',
            field=models.ManyToManyField(blank=True, null=True, related_name='houses', to='lists.Store'),
        ),
        migrations.AlterField(
            model_name='house',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='houses', to='lists.Item'),
        ),
        migrations.AlterField(
            model_name='house',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='bought_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='stores',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='lists.Store'),
        ),
        migrations.AlterField(
            model_name='link',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
