# Generated by Django 2.1.4 on 2019-02-25 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20190225_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='faveStores',
            field=models.ManyToManyField(blank=True, related_name='houses', to='lists.Store'),
        ),
        migrations.AlterField(
            model_name='house',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='houses', to='lists.Item'),
        ),
        migrations.AlterField(
            model_name='house',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='items', to='lists.Store'),
        ),
    ]
