# Generated by Django 2.1.4 on 2019-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20190225_1843'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['name'], name='lists_house_name_5f400b_idx'),
        ),
    ]
