# Generated by Django 2.1.4 on 2019-02-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20190225_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bought',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
