# Generated by Django 2.1.4 on 2019-02-25 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20190225_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
